import { Lora, Poppins } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import { auth } from '@/auth';
import { SessionProvider } from 'next-auth/react';
import './globals.css';

const lora = Lora({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-lora',
});

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-poppins',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    const session = await auth();

    return (
        <SessionProvider session={session}>
            <html lang='en'>
                <body className={`${lora.variable} ${poppins.variable}`}>
                    <Toaster />
                    {children}
                </body>
            </html>
        </SessionProvider>
    );
}
